### ISSUE TITLE
안드로이드폰 클라이언트 인증서 등록

### ISSUE THREAD

**Issue by iykkim** [SeongSikChae/Certificate#1]
안녕하세요.

같은 경험이 있으시지 않을까해서 문의 드려봅니다.

생성한 클라이언트 인증서 .p12 파일이 Windows PC에서는 등록에 문제가 없었으나, 안드로이드폰에서는 계속 잘못된 인증서이거나 암호가 틀리다고 나오고 등록이 안되는 문제가 있습니다.

버전은 안드로이드 8.1.0 오레오이며, 혹시나 해서 아주 단순한 4자리 숫자 암호로 ..p12 파일만 다시 생성해서 해봐도 동일했습니다.

물론 이 .p12 인증서 파일 역시 Windows PC에서는 등록 진행이 잘 됩니다.

혹시 같은 문제가 있었다면 어떻게 해결하셨는지 알고 싶습니다.

**Comment by SeongSikChae** [comment]
안드로이드 폰에 Root 인증서를 먼저 등록하셨는지 확인 부탁드립니다.

또한 안드로이드 버전 별로 보안 규격이 다를 수 있으므로

[ alt_names ] 내용에 전부를 주석 처리 후 재발급 해서 테스트 부탁드립니다.

**Comment by iykkim** [comment]
Root 인증서는 문제없이 등록되었었습니다.

Client.cfg의 [ alt_names ] 섹션 항목들은 이미 모두 주석 처리 되어 있으며, DNS.1과 IP.1 항목에 설정 내용도 없는 상태입니다.

아래는 실제 설정 상태입니다.

[ alt_names ]
#DNS.1	=	
#IP.1    =

**Comment by iykkim** [comment]
추가로 pkcs12 형식이 아닌 pem 형식으로 생성해서 등록을 시도해 봤는데, 암호를 묻는 단계가 없이 등록은 잘 되었지만 브라우저로 관리 서버를 열 때마다 인증서를 찾을 수 없다는 메세지가 나오고 하단의 +인증서 추가를 탭해서 추가를 해도 계속 똑같은 인증서를 못찾는다는 메세지와 인증서 추가 화면이 반복되는 상태입니다.

pem 형식 클라이언트 인증서 생성은 아래 명령으로 진행했습니다.

openssl x509 -req -days 365 -extensions v3_user_req -outform PEM -in D:\PowerManager\Certificate\certs\C.csr -CA D:\PowerManager\Certificate\newcerts\ca.crt -CAcreateserial -CAkey D:\PowerManager\Certificate\private\ca.key -out D:\PowerManager\Certificate\newcerts\C.pem -extfile D:\PowerManager\Certificate\Client.cfg

**Comment by SeongSikChae** [comment]
기존에 발급한 p12 파일을
`openssl pkcs12 -in C.p12 -nodes -nocerts -out C.pem`
형태로 변환해서 등록해보시기 바랍니다.

**Comment by iykkim** [comment]
말씀하신 대로 생성한 C.pem 파일로 인증서 등록을 시도하면 "설치할 인증서가 없습니다"라는 메세지가 나오고 인증서 설치가 안됩니다.

웹브라우저에서도 같은 메세지가 나오고, +인증서 추가 화면만 반복됩니다.

**Comment by SeongSikChae** [comment]
![2](https://user-images.githubusercontent.com/55735227/158097216-17ed1cca-f591-4c15-a82c-fd5745597f39.jpg)

ROOT 인증서는 CA 인증서에
클라이언트 인증서는 VPN 및 앱 사용자 인증서로 등록하셔야하는데

그렇게 진행되신건지 확인부탁드립니다.

**Comment by SeongSikChae** [comment]
p12파일에 확장자를 pfx로 바꿔보시고 그래도 안되시면 해당 폰 제조사에 문의를 해보셔야 할 듯 합니다.

**Comment by iykkim** [comment]
등록할 때는 모두 VPN 및 App으로 등록하면 CA는 CA 인증서, 사용자는 사용자 인증서에 등록이 되는 방식입니다.

확인해 보면 CA와 사용자 인증서에 등록되어 있습니다.

pfx 확장자로 바꿔서 시도해보면 똑같이 계속 암호를 묻기만 하고 등록이 안되는 상태입니다.

참고로 아래 사이트를 찾았는데, 이 내용이 지금으로서는 가장 비슷해 보여서 오후에 더 해보려고 합니다.

https://www.lastbreach.com/blog/importing-private-ca-certificates-in-android

이 사이트의 방법이 어떤지도 한번 검토 부탁합니다.

**Comment by SeongSikChae** [comment]
![1](https://user-images.githubusercontent.com/55735227/158101824-4c85770c-4851-465d-82f0-71b1f0a2b68a.png)
![2](https://user-images.githubusercontent.com/55735227/158101826-26663297-915a-4bd6-9da2-f53ba131c1f1.png)
![3](https://user-images.githubusercontent.com/55735227/158101812-301fd657-0332-407f-999e-131fd43e1c0b.png)
![4](https://user-images.githubusercontent.com/55735227/158101815-b8e25009-e0f3-4e98-a4cc-7a64c55dc02f.png)
![5](https://user-images.githubusercontent.com/55735227/158101816-607eccb3-00b6-40c1-9451-638378e3979f.png)
![6](https://user-images.githubusercontent.com/55735227/158101817-34bdbff8-3b39-4152-a596-a19d6452f2b9.png)
![7](https://user-images.githubusercontent.com/55735227/158101820-333e1b0e-40a5-4e1b-b904-1da2e4318dd8.png)
![8](https://user-images.githubusercontent.com/55735227/158101821-2bfa52ee-7180-4991-92bc-68187fb01f95.png)
![9](https://user-images.githubusercontent.com/55735227/158101822-ed4c6a27-f5d5-4128-8629-54d5f5508b6f.png)
![10](https://user-images.githubusercontent.com/55735227/158101823-18eeeaaf-6021-4f07-976d-0434ffa7952f.png)

**Comment by SeongSikChae** [comment]
[AzureRoot.crt.txt](https://github.com/SeongSikChae/Certificate/files/8241608/AzureRoot.crt.txt)
[iykkim.p12.txt](https://github.com/SeongSikChae/Certificate/files/8241606/iykkim.p12.txt)
[iykkim.crt.txt](https://github.com/SeongSikChae/Certificate/files/8241607/iykkim.crt.txt)

PASSWORD: qwer1234

이것으로 한번 테스트 해보시겠습니까?

**Comment by iykkim** [comment]
첨부해주신 iykkim.p12 인증서 파일은 화면 캡춰하신 내용처럼 설치가 잘 되었습니다.

또한 웹 브라우저에서도 설치된 인증서 목록에 잘 나와 선택하고 진행이 잘 됩니다.

어떤 옵션으로 openssl에서 생성하신 p12 인증 파일인지 알려 주시면, 직접 생성한 후  PM 관리 서버 페이지 연결이 잘 될거 같습니다.

**Comment by SeongSikChae** [comment]
명령어를 txt 파일에 있는대로 하셨다면

클라이언트 인증서 발급 시 이메일 정보를 등록 해보십시오.

**Comment by SeongSikChae** [comment]
`openssl genrsa -out A:\Certificate\private\iykkim.key`
`openssl req -new -key A:\Certificate\private\iykkim.key -out A:\Certificate\certs\iykkim.csr -config A:\Certificate\Client.cfg`

###
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.

Country Name (2 letter code) [KR]:
State or Province Name (full name) []:
Locality Name (eg, city) []:
Organization Name (eg, company) []:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:iykkim
Email Address []:iykkim@XXX.com

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:

`openssl x509 -req -days 365 -extensions v3_user_req -in A:\Certificate\certs\iykkim.csr -CA A:\Certificate\newcerts\TestRoot.crt -CAcreateserial -CAkey A:\Certificate\private\TestRoot.key -out A:\Certificate\newcerts\iykkim.crt -extfile A:\Certificate\Client.cfg`

`openssl pkcs12 -inkey A:\Certificate\private\iykkim.key -in A:\Certificate\newcerts\iykkim.crt -export -out A:\Certificate\newcerts\iykkim.p12`

**Comment by iykkim** [comment]
알려주신 대로 이메일 주소 추가를 하고 수 차례 시도해 봤으나, 생성한 p12 인증서 파일로 등록을 시도하면 여전히 암호 입력 화면만 반복되고 등록 진행이 안됩니다.

오늘 보내주신 테스트용 p12 인증서 파일은 잘 되는데 뭐가 다른 건지 모르겠네요...

테스트 p12 인증서 생성은 Windows 환경에서 하신 건가요 아니면 Linux 같은 다른 환경에서 진행하신 건가요?

**Comment by SeongSikChae** [comment]
Windows 환경에서 했습니다.

**Comment by SeongSikChae** [comment]
[Client.cfg.txt](https://github.com/SeongSikChae/Certificate/files/8242847/Client.cfg.txt)
[Server.cfg.txt](https://github.com/SeongSikChae/Certificate/files/8242849/Server.cfg.txt)

##
[루트인증서]

openssl genrsa -out A:\Certificate\private\AzureRoot.key
openssl req -new -key A:\Certificate\private\AzureRoot.key -out A:\Certificate\certs\AzureRoot.csr -config A:\Certificate\Server.cfg
openssl x509 -req -days 3650 -extensions v3_ca -in A:\Certificate\certs\AzureRoot.csr -signkey A:\Certificate\private\AzureRoot.key -out A:\Certificate\newcerts\AzureRoot.crt -extfile A:\Certificate\Server.cfg
openssl pkcs12 -inkey A:\Certificate\private\AzureRoot.key -in A:\Certificate\newcerts\AzureRoot.crt -export -out A:\Certificate\newcerts\AzureRoot.p12

[서버인증서]

openssl genrsa -out A:\Certificate\private\S.key
openssl req -new -key A:\Certificate\private\css5831.iptime.org.key -out A:\Certificate\certs\S.csr -config A:\Certificate\Server.cfg
openssl x509 -req -days 3650 -extensions v3_req -in A:\Certificate\certs\S.csr -CA A:\Certificate\newcerts\AzureRoot.crt -CAcreateserial -CAkey A:\Certificate\private\AzureRoot.key -out A:\Certificate\newcerts\S.crt -extfile A:\Certificate\Server.cfg
openssl pkcs12 -inkey A:\Certificate\private\S.key -in A:\Certificate\newcerts\S.crt -export -out A:\Certificate\newcerts\S.p12 -CAfile A:\Certificate\newcerts\AzureRoot.crt -chain

[클라이언트인증서]

openssl genrsa -out A:\Certificate\private\iykkim.key
openssl req -new -key A:\Certificate\private\iykkim.key -out A:\Certificate\certs\iykkim.csr -config A:\Certificate\Client.cfg
openssl x509 -req -days 365 -extensions v3_user_req -in A:\Certificate\certs\iykkim.csr -CA A:\Certificate\newcerts\AzureRoot.crt -CAcreateserial -CAkey A:\Certificate\private\AzureRoot.key -out A:\Certificate\newcerts\iykkim.crt -extfile A:\Certificate\Client.cfg
openssl pkcs12 -inkey A:\Certificate\private\iykkim.key -in A:\Certificate\newcerts\iykkim.crt -export -out A:\Certificate\newcerts\iykkim.p12

**Comment by iykkim** [comment]
Server.cfg 파일과 Client.cfg 파일도 비교해 봤지만, 설정을 해야 하는 부분 외에 모두 동일한 것을 확인했습니다.

첨부하신 위의 명령문들로 새로 만든 루트 인증서와 클라이언트 인증서를 등록해봤는데, 역시 클라이언트 iykkim.p12 파일 등록을 할 때 계속 암호 입력 창만 나오고 등록이 안됩니다.

위에 첨부하신 테스트 iykkim.p12는 잘 되고요.

어디에서 차이가 있는 건지 전혀 모르겠습니다.

작업한 제 Windows 버전은 Windows 11 Pro 21H2 빌드 22000.556 입니다.

Windows 버전이 다르면 이런 문제가 있을까요? 아니면 혹시 명령문을 실행한 cmd 창의 codepage가 다르면 이럴 수 있나요?

**Comment by SeongSikChae** [comment]
openssl 버전 탓일 수도 있을 것 같습니다.

~~Cmd에 codepage는 어떻게 되어있으신지?~~

Openssl 버전 확인 부탁드립니다.

**Comment by iykkim** [comment]
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021) 입니다.

(cmd의 codepage는 949입니다)

설치 메뉴얼의 openssl 다운로드 페이지에서 가장 처음에 있는 5MB 크기의 Light 버전으로 다운받아서 진행했습니다.

두번째의 140MB 크기 버전으로 다운받아야 할까요?

**Comment by SeongSikChae** [comment]
3.0.1 Full로 해보시고 안되시면 1.1.1 Full로 해보시겟어요?

Light 버전이라 일부 라이브러리가 빠지면서 결과물인 인증서가 달라지는게 아닌가 싶은데요

**Comment by iykkim** [comment]
1.1.1m Full 버전으로 설치해서 진행해 보니 드디어 잘 됩니다.
(3.0.1 Full 버전도 안되었습니다)

인증서를 새로 만든 관계로 다시 설정 작업을 해야 될거 같습니다.

답변과 지원에 감사드립니다.

**Comment by SeongSikChae** [comment]
Android Oreo  8 버전이  2017년 8월 22일 날 공개가 되었고
OpenSSL 3.0이 21년 9월 7일 정식 공개이므로

Oreo 8 버전 기반에 OS 커널에선 3.0 기반 인증서가 호환되지 않나봅니다.

**Comment by SeongSikChae** [comment]
[OpenSSL](https://ko.wikipedia.org/wiki/OpenSSL) Wiki

**Comment by iykkim** [comment]
OpenSSL 릴리즈 일자와는 관계가 없고 버전 호환이 안 되는거 같습니다.
설치한 OpenSSL 1.1.1m 릴리즈 일자가 아래 사이트를 보면 작년 12월 14일이거든요.

[OpenSSL 릴리즈 노트](https://www.openssl.org[/news/openssl-1.1.1-notes.html](https://www.openssl.org/news/openssl-1.1.1-notes.html))

설치 메뉴얼 업데이트 하실 때, OpenSSL은 1.1.1 버전을 설치하라는 안내를 넣으시는게 좋을거 같습니다.

**Comment by iykkim** [comment]
OpenSSL 릴리즈 일자와는 관계가 없고 버전 호환이 안 되는거 같습니다.
설치한 OpenSSL 1.1.1m 릴리즈 일자가 아래 사이트를 보면 작년 12월 14일이거든요.

[OpenSSL 릴리즈 노트](https://www.openssl.org/news/openssl-1.1.1-notes.html)

설치 메뉴얼 업데이트 하실 때, OpenSSL은 1.1.1 버전을 설치하라는 안내를 넣으시는게 좋을거 같습니다.

**Comment by iykkim** [comment]
OpenSSL 릴리즈 일자와는 관계가 없고 말씀하신 대로 버전 호환이 안 되는거 같습니다.
설치한 OpenSSL 1.1.1m 릴리즈 일자가 아래 사이트를 보면 작년 12월 14일이거든요.

[OpenSSL 릴리즈 노트](https://www.openssl.org/news/openssl-1.1.1-notes.html)

설치 메뉴얼 업데이트 하실 때, OpenSSL은 1.1.1 버전을 설치하라는 안내를 넣으시는게 좋을거 같습니다.

**Comment by SeongSikChae** [comment]
제가 말한건 단순 릴리즈 일자가 아니라 내부 코어 라이브러리가 언제 게시됬냐를 뜻한거였습니다.

1.1.1m은 최근에 나왔어도 그 기반 코어 인 1.0이 훨씬 이전에 나왔기 때문에 상관없지만 3은 8.0보다 이후에 나온거니 리눅스 커널에 반영이 안되어 있을 것 같다는 것이였습니다.

메뉴얼에는 1.1.1l로 표기가 되어있습니다.

**Comment by SeongSikChae** [comment]
Android 보면 해당 Android 버전에 맞는 리눅스 커널버전이 있는데 그거랑 openssl 간에 Dependency가 있으니 그걸 염두해 두고 인증서 발급 과정을 진행할 필요가 있어보입니다.

**Comment by iykkim** [comment]
메뉴얼 다시 보니 다운로드 링크 아래 그림 캡춰에 1.1.1로 되어 있는걸 제가 안 봤었군요.. ^^;

이전에 다른 mqtt 환경 테스트할 때 이미 설치해 놓았던 것과 같은 거였다고 생각하고 그냥 넘어간 거 같습니다.

답변 감사합니다.
